export const route_pig_iron = {
    name: "Pig Iron",
    description: "Pig Iron - Standardized factory flow grouped by production cycles",
    industryType: "CBAM",
    thumbnail: "🧱",
    nodes: [
      // Cycle groups
      {
        nodeId: "g1",
        type: "Group",
        label: "Raw Material Cycle",
        x: -82.46339550637728,
        y: 73.83553788889826,
        data: { text: "Raw Material Cycle", width: 1041.3645481880499, height: 487.28222254011814, groupTint: "#EF4444" },
      },
      { nodeId: "g2", type: "Group", label: "Raw Material Preparation Cycle", x: 1120, y: 120, data: { text: "Raw Material Preparation Cycle", width: 960, height: 420, groupTint: "#F59E0B" } },
      { nodeId: "g3", type: "Group", label: "Core Production Cycle", x: 80, y: 620, data: { text: "Core Production Cycle", width: 960, height: 420, groupTint: "#3B82F6" } },
      { nodeId: "g4", type: "Group", label: "Product Finishing Cycle", x: 1120, y: 620, data: { text: "Product Finishing Cycle", width: 960, height: 420, groupTint: "#10B981" } },
      {
        nodeId: "g5",
        type: "Group",
        label: "Energy Consumption Cycle (Reusable Utilities)",
        x: 80,
        y: 1120,
        data: { text: "Energy Consumption Cycle (Reusable Utilities)", width: 960, height: 420, groupTint: "#6366F1" },
      },
      { nodeId: "g6", type: "Group", label: "End-of-Life / Circular Cycle", x: 1120, y: 1120, data: { text: "End-of-Life / Circular Cycle", width: 960, height: 420, groupTint: "#A855F7" } },

      // 1) Raw Material Cycle
      {
        nodeId: "n1",
        type: "Material Extraction",
        label: "Iron Ore",
        x: -17.157504055687852,
        y: 437.246908359023,
        data: { scope: 3, category: "Storage & Materials", scopeType: "Scope 3", stepNo: 1, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n2",
        type: "Material Extraction",
        label: "Coal (for Coke)",
        x: -8.321897582017431,
        y: 255.74137778568095,
        data: { scope: 3, category: "Storage & Materials", scopeType: "Scope 3", stepNo: 2, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n3",
        type: "Material Extraction",
        label: "Limestone",
        x: 131.94874827234895,
        y: 118.0475270059042,
        data: { scope: 3, category: "Storage & Materials", scopeType: "Scope 3", stepNo: 3, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n4",
        type: "Material/Product Transport",
        label: "Raw Material Logistics",
        x: 418.5726588121714,
        y: 212.7859181874303,
        data: { scope: 3, category: "Transport", scopeType: "Scope 3", stepNo: 4, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n5",
        type: "Raw Material Storage",
        label: "Ore / Coal Yard",
        x: 724.2838569137638,
        y: 207.83697563337395,
        data: { scope: 1, category: "Storage & Materials", scopeType: "Scope 1", stepNo: 5, routeType: "CBAM Production Route" },
      },

      // 2) Raw Material Preparation Cycle
      {
        nodeId: "n6",
        type: "Thermal Processing Unit",
        label: "Coke Oven (Coal -> Coke)",
        x: 1190,
        y: 280,
        data: { scope: 1, category: "Thermal / Combustion", scopeType: "Scope 1", stepNo: 6, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n7",
        type: "Material Agglomeration",
        label: "Sinter Plant",
        x: 1455.4468738359815,
        y: 278.4352971502298,
        data: { scope: 1, category: "Processing", scopeType: "Scope 1", stepNo: 7, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n8",
        type: "Material Agglomeration",
        label: "Pellet Plant (optional)",
        x: 1678.6467707281681,
        y: 165.77669196677613,
        data: { scope: 1, category: "Processing", scopeType: "Scope 1", stepNo: 8, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n9",
        type: "Material Preparation",
        label: "Flux Preparation (Limestone)",
        x: 1684.3529715022983,
        y: 366.0586567373605,
        data: { scope: 1, category: "Processing", scopeType: "Scope 1", stepNo: 9, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n10",
        type: "Material Charging System",
        label: "Blast Furnace Burden",
        x: 1870,
        y: 280,
        data: { scope: 1, category: "Processing", scopeType: "Scope 1", stepNo: 10, routeType: "CBAM Production Route" },
      },

      // 3) Core Production Cycle
      {
        nodeId: "n11",
        type: "Combustion Heating System",
        label: "Hot Blast Stove",
        x: 150,
        y: 780,
        data: { scope: 1, category: "Thermal / Combustion", scopeType: "Scope 1", stepNo: 11, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n12",
        type: "Smelting Reactor",
        label: "Blast Furnace",
        x: 328.4651824840765,
        y: 780,
        data: { scope: 1, category: "Thermal / Combustion", scopeType: "Scope 1", stepNo: 12, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n13",
        type: "Metal Formation",
        label: "Pig Iron Formation",
        x: 501.5561205105331,
        y: 780,
        data: { scope: 1, category: "Processing", scopeType: "Scope 1", stepNo: 13, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n14",
        type: "By-product Separation",
        label: "Slag Separation",
        x: 683.7025109554141,
        y: 780,
        data: { scope: 1, category: "Processing", scopeType: "Scope 1", stepNo: 14, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n15",
        type: "Molten Metal Handling",
        label: "Hot Metal Transfer",
        x: 868.9398394267519,
        y: 780,
        data: { scope: 1, category: "Transport", scopeType: "Scope 1", stepNo: 15, routeType: "CBAM Production Route" },
      },

      // 4) Product Finishing Cycle
      {
        nodeId: "n16",
        type: "Casting Unit",
        label: "Pig Casting Machine",
        x: 1195.4545727043035,
        y: 776.363618197131,
        data: { scope: 1, category: "Processing", scopeType: "Scope 1", stepNo: 16, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n17",
        type: "Cooling System",
        label: "Pig Iron Solidification",
        x: 1427.2730633530764,
        y: 776.363618197131,
        data: { scope: 2, category: "Cooling & Utilities", scopeType: "Scope 2", stepNo: 17, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n18",
        type: "Warehouse/Finished Product Storage",
        label: "Pig Iron Yard",
        x: 1626.3641177760285,
        y: 778.1818090985655,
        data: { scope: 1, category: "Storage & Materials", scopeType: "Scope 1", stepNo: 18, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n19",
        type: "Material/Product Transport",
        label: "Pig Iron Dispatch",
        x: 1854.5462266219324,
        y: 780,
        data: { scope: 3, category: "Transport", scopeType: "Scope 3", stepNo: 19, routeType: "CBAM Production Route" },
      },

      // 5) Energy Consumption Cycle (Reusable Utilities)
      {
        nodeId: "n20",
        type: "Electricity Supply",
        label: "Grid / Captive Power",
        x: 150,
        y: 1280,
        data: { scope: 2, category: "Energy Sources & Grid", scopeType: "Scope 2", stepNo: 20, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n21",
        type: "Fuel Combustion System",
        label: "Boilers",
        x: 320,
        y: 1280,
        data: { scope: 1, category: "Thermal / Combustion", scopeType: "Scope 1", stepNo: 21, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n22",
        type: "Process Gas Recovery",
        label: "Blast Furnace Gas",
        x: 490,
        y: 1280,
        data: { scope: 1, category: "Energy Sources & Grid", scopeType: "Scope 1", stepNo: 22, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n23",
        type: "Compressed Air System",
        label: "Air Compressors",
        x: 660,
        y: 1280,
        data: { scope: 2, category: "Power & Electrical", scopeType: "Scope 2", stepNo: 23, routeType: "CBAM Production Route" },
      },
      {
        nodeId: "n24",
        type: "Cooling Water System",
        label: "Water Circulation",
        x: 830,
        y: 1280,
        data: { scope: 2, category: "Cooling & Utilities", scopeType: "Scope 2", stepNo: 24, routeType: "CBAM Production Route" },
      },

      // 6) End-of-Life / Circular Cycle
      {
        nodeId: "n25",
        type: "Downstream Processing",
        label: "Steelmaking (BOF / Foundry)",
        x: 1240,
        y: 1280,
        data: { scope: 3, category: "Processing", scopeType: "Scope 3", stepNo: 25, routeType: "CBAM Production Route" },
      },
      { nodeId: "n26", type: "Scrap Generation", label: "Steel Scrap", x: 1460, y: 1280, data: { scope: 3, category: "Other", scopeType: "Scope 3", stepNo: 26, routeType: "CBAM Production Route" } },
      {
        nodeId: "n27",
        type: "Recycling Process",
        label: "Scrap -> Steel",
        x: 1680,
        y: 1280,
        data: { scope: 3, category: "Processing", scopeType: "Scope 3", stepNo: 27, routeType: "CBAM Production Route" },
      },
    ],
    edges: [
      // Raw Material Cycle
      { edgeId: "e1", source: "n1", target: "n4", type: "material", label: "Iron Ore" },
      { edgeId: "e2", source: "n2", target: "n4", type: "material", label: "Coal" },
      { edgeId: "e3", source: "n3", target: "n4", type: "material", label: "Limestone" },
      { edgeId: "e4", source: "n4", target: "n5", type: "material", label: "Raw Material Logistics" },

      // Raw Material Preparation Cycle
      { edgeId: "e5", source: "n5", target: "n6", type: "material", label: "Feed" },
      { edgeId: "e6", source: "n6", target: "n7", type: "material", label: "Prepared Feed" },
      { edgeId: "e7", source: "n7", target: "n10", type: "material", label: "Sinter" },
      { edgeId: "e8", source: "n8", target: "n10", type: "material", label: "Pellets" },
      { edgeId: "e9", source: "n9", target: "n10", type: "material", label: "Flux" },

      // Core Production Cycle
      { edgeId: "e10", source: "n10", target: "n11", type: "material", label: "Burden" },
      { edgeId: "e11", source: "n11", target: "n12", type: "steam", label: "Hot Blast" },
      { edgeId: "e12", source: "n12", target: "n13", type: "material", label: "Molten Iron" },
      { edgeId: "e13", source: "n13", target: "n14", type: "material", label: "Separation" },
      { edgeId: "e14", source: "n14", target: "n15", type: "material", label: "Hot Metal" },

      // Product Finishing Cycle
      { edgeId: "e15", source: "n15", target: "n16", type: "material", label: "Cast Feed" },
      { edgeId: "e16", source: "n16", target: "n17", type: "water", label: "Cooling" },
      { edgeId: "e17", source: "n17", target: "n18", type: "material", label: "Solid Pig Iron" },
      { edgeId: "e18", source: "n18", target: "n19", type: "material", label: "Dispatch" },

      // Utilities into process
      { edgeId: "e19", source: "n20", target: "n11", type: "electrical", label: "Power" },
      { edgeId: "e20", source: "n21", target: "n11", type: "steam", label: "Boiler Heat" },
      { edgeId: "e21", source: "n22", target: "n12", type: "gas", label: "BF Gas" },
      { edgeId: "e22", source: "n23", target: "n11", type: "electrical", label: "Compressed Air" },
      { edgeId: "e23", source: "n24", target: "n17", type: "water", label: "Cooling Water" },

      // Circular loop
      { edgeId: "e24", source: "n19", target: "n25", type: "material", label: "Downstream Feed" },
      { edgeId: "e25", source: "n25", target: "n26", type: "material", label: "Scrap" },
      { edgeId: "e26", source: "n26", target: "n27", type: "material", label: "Recycle" },
      { edgeId: "e27", source: "n27", target: "n4", type: "material", label: "Recycled Feed" },
    ],
  };
