export const INDUSTRY_PRESETS = {
  "steel-foundry": {
    name: "Steel Industry — Foundry",
    description: "Foundry process: melting, casting, heat treatment, and finishing",
    industryType: "Steel",
    thumbnail: "🏭",
    nodes: [
      { nodeId: "n1", type: "Raw Material Storage", label: "Raw Material Store", x: 60, y: 220, data: {} },
      { nodeId: "n2", type: "Fuel Storage", label: "Fuel Storage", x: 60, y: 380, data: {} },
      { nodeId: "n3", type: "Induction Furnace", label: "Induction Furnace", x: 300, y: 220, data: { capacity: 10, capacityUnit: "TPH" } },
      { nodeId: "n4", type: "Ladle", label: "Ladle Refining", x: 530, y: 220, data: {} },
      { nodeId: "n5", type: "Moulding", label: "Moulding / Casting", x: 760, y: 220, data: {} },
      { nodeId: "n6", type: "Heat Treatment", label: "Heat Treatment", x: 990, y: 220, data: {} },
      { nodeId: "n7", type: "Finishing", label: "Finishing", x: 1220, y: 220, data: {} },
      { nodeId: "n8", type: "Quality Inspection", label: "Quality Check", x: 1220, y: 380, data: {} },
      { nodeId: "n9", type: "Warehouse", label: "Finished Goods", x: 1450, y: 300, data: {} },
      { nodeId: "n10", type: "Cooling Tower", label: "Cooling System", x: 530, y: 60, data: {} },
      { nodeId: "n11", type: "Transformer", label: "Power Supply", x: 300, y: 60, data: {} },
    ],
    edges: [
      { edgeId: "e1", source: "n1", target: "n3", type: "material", label: "Scrap / Metal" },
      { edgeId: "e2", source: "n2", target: "n3", type: "energy", label: "Fuel" },
      { edgeId: "e3", source: "n3", target: "n4", type: "material", label: "Molten Metal" },
      { edgeId: "e4", source: "n4", target: "n5", type: "material", label: "Refined Metal" },
      { edgeId: "e5", source: "n5", target: "n6", type: "material", label: "Cast Parts" },
      { edgeId: "e6", source: "n6", target: "n7", type: "material", label: "Treated Parts" },
      { edgeId: "e7", source: "n7", target: "n9", type: "material", label: "Finished" },
      { edgeId: "e8", source: "n7", target: "n8", type: "material", label: "For QC" },
      { edgeId: "e9", source: "n8", target: "n9", type: "material", label: "Approved" },
      { edgeId: "e10", source: "n10", target: "n3", type: "water", label: "Cooling Water" },
      { edgeId: "e11", source: "n11", target: "n3", type: "electrical", label: "Power" },
    ],
  },
  "steel-rolling": {
    name: "Steel Industry — Rolling Mill",
    description: "Hot/cold rolling process for bars, rods, and sheets",
    industryType: "Steel",
    thumbnail: "🔩",
    nodes: [
      { nodeId: "n1", type: "Raw Material Storage", label: "Billet / Slab Yard", x: 60, y: 220, data: {} },
      { nodeId: "n2", type: "Reheating Furnace", label: "Reheating Furnace", x: 300, y: 220, data: { capacity: 50, capacityUnit: "TPH" } },
      { nodeId: "n3", type: "Rolling Mill", label: "Roughing Mill", x: 560, y: 150, data: {} },
      { nodeId: "n4", type: "Rolling Mill", label: "Finishing Mill", x: 560, y: 320, data: {} },
      { nodeId: "n5", type: "Cooling Bed", label: "Cooling Bed", x: 810, y: 220, data: {} },
      { nodeId: "n6", type: "Shearing", label: "Shearing / Cutting", x: 1040, y: 220, data: {} },
      { nodeId: "n7", type: "Quality Inspection", label: "Quality Check", x: 1270, y: 220, data: {} },
      { nodeId: "n8", type: "Warehouse", label: "Product Storage", x: 1500, y: 220, data: {} },
      { nodeId: "n9", type: "Fuel Storage", label: "Natural Gas", x: 300, y: 60, data: {} },
      { nodeId: "n10", type: "Cooling Tower", label: "Cooling Tower", x: 810, y: 60, data: {} },
      { nodeId: "n11", type: "Transformer", label: "HT Power", x: 60, y: 60, data: {} },
    ],
    edges: [
      { edgeId: "e1", source: "n1", target: "n2", type: "material", label: "Billets" },
      { edgeId: "e2", source: "n9", target: "n2", type: "energy", label: "NG Fuel" },
      { edgeId: "e3", source: "n2", target: "n3", type: "material", label: "Hot Billet" },
      { edgeId: "e4", source: "n3", target: "n4", type: "material", label: "Roughed" },
      { edgeId: "e5", source: "n4", target: "n5", type: "material", label: "Rolled" },
      { edgeId: "e6", source: "n5", target: "n6", type: "material", label: "Cooled" },
      { edgeId: "e7", source: "n6", target: "n7", type: "material", label: "Cut Product" },
      { edgeId: "e8", source: "n7", target: "n8", type: "material", label: "Approved" },
      { edgeId: "e9", source: "n10", target: "n5", type: "water", label: "Cooling" },
      { edgeId: "e10", source: "n11", target: "n3", type: "electrical", label: "Power" },
      { edgeId: "e11", source: "n11", target: "n4", type: "electrical", label: "Power" },
    ],
  },
  "steel-forging": {
    name: "Steel Industry — Forging",
    description: "Forging process: heating, pressing, treatment, and machining",
    industryType: "Steel",
    thumbnail: "⚒️",
    nodes: [
      { nodeId: "n1", type: "Raw Material Storage", label: "Bar / Billet Stock", x: 60, y: 220, data: {} },
      { nodeId: "n2", type: "Heater", label: "Induction Heater", x: 300, y: 220, data: { capacity: 2, capacityUnit: "MW" } },
      { nodeId: "n3", type: "Forging Press", label: "Forging Press", x: 540, y: 220, data: { capacity: 1600, capacityUnit: "units" } },
      { nodeId: "n4", type: "Heat Treatment", label: "Heat Treatment", x: 780, y: 220, data: {} },
      { nodeId: "n5", type: "Machining", label: "CNC Machining", x: 1020, y: 220, data: {} },
      { nodeId: "n6", type: "Quality Inspection", label: "Inspection", x: 1260, y: 220, data: {} },
      { nodeId: "n7", type: "Dispatch", label: "Dispatch", x: 1480, y: 220, data: {} },
      { nodeId: "n8", type: "Transformer", label: "Power Supply", x: 300, y: 60, data: {} },
      { nodeId: "n9", type: "Cooling Tower", label: "Cooling System", x: 780, y: 60, data: {} },
      { nodeId: "n10", type: "Compressor", label: "Air Compressor", x: 540, y: 60, data: {} },
    ],
    edges: [
      { edgeId: "e1", source: "n1", target: "n2", type: "material", label: "Billets" },
      { edgeId: "e2", source: "n2", target: "n3", type: "material", label: "Heated" },
      { edgeId: "e3", source: "n3", target: "n4", type: "material", label: "Forged" },
      { edgeId: "e4", source: "n4", target: "n5", type: "material", label: "Treated" },
      { edgeId: "e5", source: "n5", target: "n6", type: "material", label: "Machined" },
      { edgeId: "e6", source: "n6", target: "n7", type: "material", label: "Approved" },
      { edgeId: "e7", source: "n8", target: "n2", type: "electrical", label: "Power" },
      { edgeId: "e8", source: "n8", target: "n3", type: "electrical", label: "Power" },
      { edgeId: "e9", source: "n9", target: "n4", type: "water", label: "Cooling" },
      { edgeId: "e10", source: "n10", target: "n3", type: "gas", label: "Compressed Air" },
    ],
  },
  "power-plant": {
    name: "Power Generation Plant",
    description: "Thermal power plant with boiler, turbine, and generator cycle",
    industryType: "Power",
    thumbnail: "⚡",
    nodes: [
      { nodeId: "n1", type: "Fuel Storage", label: "Coal / Gas Yard", x: 60, y: 220, data: {} },
      { nodeId: "n2", type: "Boiler", label: "Boiler", x: 300, y: 220, data: { capacity: 200, capacityUnit: "MW" } },
      { nodeId: "n3", type: "Steam Turbine", label: "Steam Turbine", x: 560, y: 220, data: {} },
      { nodeId: "n4", type: "Generator", label: "Generator", x: 800, y: 220, data: {} },
      { nodeId: "n5", type: "Transformer", label: "Step-up Transformer", x: 1040, y: 220, data: {} },
      { nodeId: "n6", type: "Dispatch", label: "Grid Connection", x: 1280, y: 220, data: {} },
      { nodeId: "n7", type: "Cooling Tower", label: "Cooling Tower", x: 560, y: 60, data: {} },
      { nodeId: "n8", type: "Water Treatment Plant", label: "DM Water Plant", x: 300, y: 60, data: {} },
      { nodeId: "n9", type: "Effluent Treatment Plant", label: "Ash Handling", x: 300, y: 400, data: {} },
    ],
    edges: [
      { edgeId: "e1", source: "n1", target: "n2", type: "material", label: "Fuel" },
      { edgeId: "e2", source: "n2", target: "n3", type: "steam", label: "Steam" },
      { edgeId: "e3", source: "n3", target: "n4", type: "energy", label: "Mech. Power" },
      { edgeId: "e4", source: "n4", target: "n5", type: "electrical", label: "Electricity" },
      { edgeId: "e5", source: "n5", target: "n6", type: "electrical", label: "HV Power" },
      { edgeId: "e6", source: "n7", target: "n3", type: "water", label: "Cooling" },
      { edgeId: "e7", source: "n8", target: "n2", type: "water", label: "Feed Water" },
      { edgeId: "e8", source: "n2", target: "n9", type: "material", label: "Ash / Waste" },
    ],
  },
  "manufacturing-general": {
    name: "General Manufacturing",
    description: "Generic manufacturing flow with processing, quality, and dispatch",
    industryType: "Manufacturing",
    thumbnail: "🏗️",
    nodes: [
      { nodeId: "n1", type: "Raw Material Storage", label: "Raw Material", x: 60, y: 200, data: {} },
      { nodeId: "n2", type: "Custom Process", label: "Processing Unit", x: 320, y: 200, data: {} },
      { nodeId: "n3", type: "Custom Process", label: "Assembly", x: 580, y: 200, data: {} },
      { nodeId: "n4", type: "Quality Inspection", label: "Quality Check", x: 840, y: 200, data: {} },
      { nodeId: "n5", type: "Packaging", label: "Packaging", x: 1100, y: 200, data: {} },
      { nodeId: "n6", type: "Warehouse", label: "Warehouse", x: 1350, y: 200, data: {} },
      { nodeId: "n7", type: "Boiler", label: "Boiler / Heater", x: 320, y: 60, data: {} },
      { nodeId: "n8", type: "Transformer", label: "Power Supply", x: 60, y: 60, data: {} },
    ],
    edges: [
      { edgeId: "e1", source: "n1", target: "n2", type: "material", label: "Raw Input" },
      { edgeId: "e2", source: "n2", target: "n3", type: "material", label: "WIP" },
      { edgeId: "e3", source: "n3", target: "n4", type: "material", label: "Assembled" },
      { edgeId: "e4", source: "n4", target: "n5", type: "material", label: "Approved" },
      { edgeId: "e5", source: "n5", target: "n6", type: "material", label: "Packed" },
      { edgeId: "e6", source: "n7", target: "n2", type: "steam", label: "Process Heat" },
      { edgeId: "e7", source: "n8", target: "n2", type: "electrical", label: "Power" },
      { edgeId: "e8", source: "n8", target: "n3", type: "electrical", label: "Power" },
    ],
  },
};

// ─── Map production route categories to predefined NODE_TYPE keys ────────────
