export const DEFAULT_CAPACITY_UNITS = {
  Boiler: "TPH",
  Furnace: "TPH",
  "Reheating Furnace": "TPH",
  "Induction Furnace": "TPH",
  Kiln: "TPH",
  Oven: "TPH",
  Heater: "MW",
  Incinerator: "TPH",
  "Flare Stack": "kg/hr",
  Turbine: "MW",
  "Steam Turbine": "MW",
  Generator: "MW",
  Transformer: "MVA",
  "Solar Panel Array": "kWp",
  "Power Grid": "MW",
  "Wind Turbine": "MW",
  "Diesel Generator": "kVA",
  "Captive Power Plant": "MW",
  "Battery Storage": "kWh",
  Inverter: "kW",
  Substation: "MVA",
  Motor: "HP",
  "CHP / Cogeneration": "MW",
  "Biogas Plant": "m³/hr",
  "Biomass Unit": "TPH",
  "Rolling Mill": "TPH",
  "Forging Press": "tons",
  "Casting Machine": "TPH",
  "Continuous Caster": "TPH",
  Machining: "units/hr",
  Ladle: "TPH",
  "Cooling Tower": "TR",
  Chiller: "TR",
  "HVAC System": "TR",
  Compressor: "CFM",
  Pump: "m³/hr",
  "Water Treatment Plant": "m³/hr",
  "Effluent Treatment Plant": "m³/hr",
};

export const CAPACITY_UNIT_OPTIONS = [
  "MW",
  "kW",
  "kWp",
  "kWh",
  "MWh",
  "MU",
  "MVA",
  "kVA",
  "MV",
  "kV",
  "MVK",
  "HP",
  "TPH",
  "TPD",
  "TPA",
  "kg/hr",
  "tons",
  "m³/hr",
  "m³/day",
  "litres/hr",
  "TR",
  "CFM",
  "units/hr",
  "units",
];

// ─── Fuel / Energy source suggestions by node type ─────────────────────────
export const DEFAULT_FUEL_OPTIONS = [
  "Diesel",
  "Petrol",
  "Natural Gas",
  "LPG",
  "CNG",
  "Coal",
  "Pet Coke",
  "Furnace Oil",
  "HSD",
  "Biomass",
  "Bagasse",
  "Rice Husk",
  "Electricity",
  "Steam",
  "Compressed Air",
  "Hydrogen",
  "Other",
];

export const NODE_FUEL_OPTIONS = {
  Boiler: ["Natural Gas", "Coal", "Furnace Oil", "Diesel", "Biomass", "Bagasse", "LPG", "Other"],
  Furnace: ["Natural Gas", "Coal", "Furnace Oil", "Pet Coke", "LPG", "Hydrogen", "Other"],
  "Reheating Furnace": ["Natural Gas", "Furnace Oil", "LPG", "Hydrogen", "Other"],
  "Induction Furnace": ["Electricity", "Natural Gas", "Hydrogen", "Other"],
  Kiln: ["Coal", "Pet Coke", "Natural Gas", "Biomass", "Rice Husk", "Bagasse", "Other"],
  Oven: ["Natural Gas", "LPG", "Diesel", "Electricity", "Other"],
  Heater: ["Natural Gas", "LPG", "Furnace Oil", "Diesel", "Electricity", "Other"],
  Incinerator: ["Diesel", "Natural Gas", "Biomass", "Other"],
  "Flare Stack": ["Natural Gas", "Refinery Gas", "Other"],
  Generator: ["Diesel", "Natural Gas", "HSD", "Other"],
  "Diesel Generator": ["Diesel", "HSD", "Other"],
  "Biogas Plant": ["Biogas", "Biomass", "Other"],
  "Biomass Unit": ["Biomass", "Wood", "Bagasse", "Rice Husk", "Other"],
  "CHP / Cogeneration": ["Natural Gas", "Coal", "Biomass", "Bagasse", "Other"],
  "Captive Power Plant": ["Coal", "Natural Gas", "Diesel", "Furnace Oil", "Pet Coke", "Other"],
  "Fuel Storage": ["Diesel", "Furnace Oil", "HSD", "LPG", "Petrol", "Kerosene", "Natural Gas", "Other"],
  Turbine: ["Steam", "Natural Gas", "Other"],
  "Steam Turbine": ["Steam", "Other"],
  Transformer: ["Electricity", "Other"],
  "Power Grid": ["Electricity", "Other"],
  "Wind Turbine": ["Wind", "Electricity", "Other"],
  "Solar Panel Array": ["Solar", "Electricity", "Other"],
  Substation: ["Electricity", "Other"],
  Inverter: ["Electricity", "Other"],
  Motor: ["Electricity", "Other"],
  Compressor: ["Electricity", "Compressed Air", "Other"],
  Pump: ["Electricity", "Water", "Other"],
  "Cooling Tower": ["Electricity", "Water", "Other"],
  Chiller: ["Electricity", "Water", "Other"],
  "HVAC System": ["Electricity", "Natural Gas", "Other"],
  Vehicle: ["Diesel", "Petrol", "CNG", "LPG", "Electricity", "Other"],
  Conveyor: ["Electricity", "Other"],
};

export const DEFAULT_UNIT_OPTIONS = ["Litres", "kg", "Tonnes", "m3", "m³", "SCM", "kWh", "MWh", "GJ", "MMBTU", "Nm3", "L", "kL", "Gallons", "Other"];

export const SOURCE_UNIT_OPTIONS = {
  Diesel: ["Litres", "L", "kL", "Gallons", "kg", "Tonnes", "Other"],
  Petrol: ["Litres", "L", "kL", "Gallons", "kg", "Tonnes", "Other"],
  HSD: ["Litres", "L", "kL", "Gallons", "kg", "Tonnes", "Other"],
  Kerosene: ["Litres", "L", "kL", "Gallons", "kg", "Tonnes", "Other"],
  "Furnace Oil": ["Litres", "L", "kL", "kg", "Tonnes", "Other"],
  Coal: ["kg", "Tonnes", "Other"],
  "Pet Coke": ["kg", "Tonnes", "Other"],
  Biomass: ["kg", "Tonnes", "Other"],
  Bagasse: ["kg", "Tonnes", "Other"],
  "Rice Husk": ["kg", "Tonnes", "Other"],
  Wood: ["kg", "Tonnes", "Other"],
  "Natural Gas": ["SCM", "Nm3", "m3", "m³", "MMBTU", "GJ", "Other"],
  LPG: ["kg", "Tonnes", "Litres", "L", "kL", "Other"],
  CNG: ["kg", "SCM", "Nm3", "m3", "m³", "Other"],
  Biogas: ["SCM", "Nm3", "m3", "m³", "Other"],
  Hydrogen: ["kg", "Tonnes", "Nm3", "SCM", "Other"],
  Electricity: ["kWh", "MWh", "MU", "MW", "kW", "MVA", "kVA", "MV", "kV", "MVK", "GJ", "Other"],
  Steam: ["kg", "Tonnes", "Other"],
  Water: ["m3", "m³", "Litres", "L", "kL", "Other"],
  Wind: ["kWh", "MWh", "MU", "MW", "kW", "GJ", "Other"],
  Solar: ["kWh", "MWh", "MU", "MW", "kW", "GJ", "Other"],
  "Compressed Air": ["Nm3", "m3", "m³", "SCM", "Other"],
};
